services:
  - type: web
    name: roblox-obby-sim
    runtime: node
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
    autoDeploy: true
